### ISSUE TITLE
Using AHB vs APB for GPIO

### ISSUE THREAD

**Issue by blakejakopovic** [particle-iot-archived/core-common-lib#26]
I'm extremely new to systems programming, but I had a quick look at the firmware and while you seem to be using the AHB for the CC3000, it doesn't seem to be used for anything else (like the GPIO). Would it make sense to look at using the AHB? 

It may not make sense in this case. I also don't know what kind of resource/performance benefits would result.

**Comment by towynlin** [comment]
Thanks for the question @blakejakopovic! Each of the peripherals that's available on the STM32 uses a specific bus.  There's a helpful table in the STM32F103 Reference Manual, available from ST here:

http://www.st.com/web/en/resource/technical/document/reference_manual/CD00171190.pdf

Or in our GitHub repository for the Spark Core hardware here:

https://github.com/spark/core/blob/master/Datasheets/Manuals/STM32F10X-reference-manual.pdf

In the reference manual, section 3 is titled "Memory and bus architecture", and section 3.3, titled "Memory map", includes Table 3 "Register boundary addresses", where the 3rd column is "Bus".

This table starts on page 50 of the PDF and covers 3 pages, where each page is grouped together by bus and memory address range.  Page 50 has everything on the AHB bus. Page 51 includes all the GPIO ports on APB2, and page 52 lists all the peripherals that use APB1.

We call out AHB in our code in a couple places. Once for CRC calculations, and then, as you point out, for DMA1, used by the CC3000 to transfer data in and out of the Wi-Fi module efficiently.

I hope that clarifies things a bit. Let us know if you have more questions!

**Comment by blakejakopovic** [comment]
Thanks for your explaination :+1:
